"""
Enso Atlas - Server-side PDF Export

Generates professional tumor board PDF reports.

Two implementations:
  - generate_pdf_report()  -- full-featured, requires ReportLab (heavyweight)
  - generate_report_pdf()  -- lightweight, uses fpdf2 (pure Python, no system deps)
"""

import io
import logging
from datetime import datetime
from pathlib import Path
from typing import Optional, List, Dict, Any

logger = logging.getLogger(__name__)

# ReportLab imports are optional - only needed for the legacy generate_pdf_report()
try:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4, letter
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch, mm
    from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
    from reportlab.platypus import (
        SimpleDocTemplate,
        Paragraph,
        Spacer,
        Table,
        TableStyle,
        Image as RLImage,
        PageBreak,
        KeepTogether,
        HRFlowable,
    )
    from reportlab.graphics.shapes import Drawing, Rect
    from reportlab.pdfgen import canvas
    from PIL import Image
    import numpy as np
    _REPORTLAB_AVAILABLE = True
except ImportError:
    _REPORTLAB_AVAILABLE = False

# Colors (only available when ReportLab is installed)
if _REPORTLAB_AVAILABLE:
    ENSO_BLUE = colors.Color(0/255, 102/255, 153/255)
    ENSO_BLUE_LIGHT = colors.Color(230/255, 242/255, 250/255)
    RESPONDER_GREEN = colors.Color(34/255, 139/255, 34/255)
    NON_RESPONDER_RED = colors.Color(178/255, 34/255, 34/255)
    WARNING_AMBER = colors.Color(255/255, 193/255, 7/255)
    WARNING_AMBER_BG = colors.Color(255/255, 248/255, 225/255)


if not _REPORTLAB_AVAILABLE:
    # Provide stubs so imports don't break when ReportLab is missing.
    # The only public function from the ReportLab path is generate_pdf_report.
    def generate_pdf_report(**kwargs):  # type: ignore[misc]
        raise RuntimeError(
            "generate_pdf_report requires ReportLab. "
            "Install it with: pip install reportlab>=4.0.0"
        )

# ---- begin ReportLab-based implementation (guarded by _REPORTLAB_AVAILABLE) ----

def create_header_footer(canvas_obj, doc):
    """Add header and footer to each page."""
    canvas_obj.saveState()
    
    page_width, page_height = doc.pagesize
    
    # Header background
    canvas_obj.setFillColor(ENSO_BLUE)
    canvas_obj.rect(0, page_height - 40*mm, page_width, 40*mm, fill=1)
    
    # Header text
    canvas_obj.setFillColor(colors.white)
    canvas_obj.setFont("Helvetica-Bold", 16)
    canvas_obj.drawString(20*mm, page_height - 18*mm, "Pathology Analysis Report")
    
    canvas_obj.setFont("Helvetica", 10)
    canvas_obj.drawString(20*mm, page_height - 26*mm, "Enso Atlas | AI-Assisted Diagnostic Platform")
    
    # Date on right
    canvas_obj.drawRightString(page_width - 20*mm, page_height - 18*mm, 
                               datetime.now().strftime("%Y-%m-%d %H:%M"))
    
    # Footer
    canvas_obj.setFillColor(colors.gray)
    canvas_obj.setFont("Helvetica", 8)
    canvas_obj.drawCentredString(page_width/2, 15*mm, 
                                  f"Page {doc.page} | Generated by Enso Atlas v0.1.0 | For Research Use Only")
    
    canvas_obj.restoreState()


def get_styles():
    """Get custom paragraph styles."""
    styles = getSampleStyleSheet()
    
    # Custom styles
    styles.add(ParagraphStyle(
        name='SectionHeader',
        parent=styles['Heading2'],
        fontSize=12,
        textColor=ENSO_BLUE,
        spaceAfter=6,
        spaceBefore=12,
        borderWidth=0,
        borderPadding=0,
        borderColor=ENSO_BLUE,
        borderRadius=0,
    ))
    
    styles.add(ParagraphStyle(
        name='SubHeader',
        parent=styles['Heading3'],
        fontSize=10,
        textColor=colors.black,
        spaceAfter=4,
        spaceBefore=8,
    ))
    
    styles.add(ParagraphStyle(
        name='EnsoBody',
        parent=styles['Normal'],
        fontSize=10,
        leading=14,
        alignment=TA_JUSTIFY,
        spaceAfter=6,
    ))
    # Also update the default BodyText
    styles['BodyText'].fontSize = 10
    styles['BodyText'].leading = 14
    styles['BodyText'].alignment = TA_JUSTIFY
    styles['BodyText'].spaceAfter = 6
    
    styles.add(ParagraphStyle(
        name='SmallText',
        parent=styles['Normal'],
        fontSize=8,
        leading=10,
        textColor=colors.gray,
    ))
    
    styles.add(ParagraphStyle(
        name='WarningText',
        parent=styles['Normal'],
        fontSize=9,
        leading=12,
        textColor=colors.Color(153/255, 102/255, 0),
        backColor=WARNING_AMBER_BG,
    ))
    
    styles.add(ParagraphStyle(
        name='PredictionResponder',
        parent=styles['Heading1'],
        fontSize=14,
        textColor=RESPONDER_GREEN,
        alignment=TA_LEFT,
    ))
    
    styles.add(ParagraphStyle(
        name='PredictionNonResponder',
        parent=styles['Heading1'],
        fontSize=14,
        textColor=NON_RESPONDER_RED,
        alignment=TA_LEFT,
    ))
    
    return styles


def create_info_table(data: List[List[str]], col_widths: List[float]) -> Table:
    """Create a styled info table."""
    table = Table(data, colWidths=col_widths)
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.Color(245/255, 245/255, 245/255)),
        ('TEXTCOLOR', (0, 0), (0, -1), colors.black),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('ALIGN', (0, 0), (0, -1), 'RIGHT'),
        ('ALIGN', (1, 0), (1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]))
    return table


def generate_pdf_report(
    slide_id: str,
    report_data: Dict[str, Any],
    prediction_data: Dict[str, Any],
    heatmap_image: Optional[bytes] = None,
    evidence_patches: Optional[List[Dict[str, Any]]] = None,
    institution_name: str = "Enso Labs",
    patient_context: Optional[Dict[str, Any]] = None,
) -> bytes:
    """
    Generate a professional PDF report for tumor board presentation.
    
    Args:
        slide_id: Slide identifier
        report_data: Structured report from MedGemma (StructuredReport dict)
        prediction_data: Model prediction results
        heatmap_image: PNG bytes of attention heatmap
        evidence_patches: List of evidence patch data with images
        institution_name: Institution name for header
        patient_context: Patient demographic info
    
    Returns:
        PDF file as bytes
    """
    buffer = io.BytesIO()
    
    # Create document
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=20*mm,
        leftMargin=20*mm,
        topMargin=45*mm,  # Space for header
        bottomMargin=25*mm,
    )
    
    styles = get_styles()
    story = []
    
    # ========== UNCALIBRATED WARNING ==========
    warning_text = """
    <b>⚠ UNCALIBRATED MODEL - RESEARCH USE ONLY</b><br/>
    Probabilities are raw model outputs. Not validated for clinical decision-making.
    All findings must be verified by qualified pathologists before clinical use.
    """
    warning_para = Paragraph(warning_text, styles['WarningText'])
    warning_table = Table([[warning_para]], colWidths=[170*mm])
    warning_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), WARNING_AMBER_BG),
        ('BOX', (0, 0), (-1, -1), 2, WARNING_AMBER),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(warning_table)
    story.append(Spacer(1, 10*mm))
    
    # ========== CASE INFORMATION ==========
    story.append(Paragraph("Case Information", styles['SectionHeader']))
    
    case_id = report_data.get('caseId', 'N/A')
    generated_at = report_data.get('generatedAt', datetime.now().isoformat())
    task = report_data.get('task', 'Treatment Response Prediction')
    
    info_data = [
        ['Case ID:', case_id],
        ['Slide ID:', slide_id],
        ['Task:', task],
        ['Generated:', datetime.fromisoformat(generated_at.replace('Z', '+00:00')).strftime('%Y-%m-%d %H:%M UTC') if generated_at else 'N/A'],
    ]
    
    story.append(create_info_table(info_data, [35*mm, 130*mm]))
    story.append(Spacer(1, 6*mm))
    
    # ========== PATIENT CONTEXT ==========
    if patient_context:
        story.append(Paragraph("Patient Information", styles['SectionHeader']))
        
        patient_data = []
        if patient_context.get('age'):
            patient_data.append(['Age:', str(patient_context['age'])])
        if patient_context.get('sex'):
            patient_data.append(['Sex:', patient_context['sex']])
        if patient_context.get('stage'):
            patient_data.append(['Stage:', patient_context['stage']])
        if patient_context.get('grade'):
            patient_data.append(['Grade:', patient_context['grade']])
        if patient_context.get('histology'):
            patient_data.append(['Histology:', patient_context['histology']])
        if patient_context.get('prior_lines') is not None:
            patient_data.append(['Prior Lines:', str(patient_context['prior_lines'])])
        
        if patient_data:
            story.append(create_info_table(patient_data, [35*mm, 130*mm]))
            story.append(Spacer(1, 6*mm))
    
    # ========== MODEL PREDICTION ==========
    story.append(Paragraph("Model Prediction", styles['SectionHeader']))
    
    model_output = report_data.get('modelOutput', prediction_data)
    label = model_output.get('label', prediction_data.get('prediction', 'Unknown'))
    score = model_output.get('score', prediction_data.get('score', 0))
    confidence = model_output.get('confidence', prediction_data.get('confidence', 0))
    
    # Determine style based on prediction
    is_responder = 'responder' in label.lower() and 'non' not in label.lower()
    pred_style = styles['PredictionResponder'] if is_responder else styles['PredictionNonResponder']
    
    story.append(Paragraph(f"<b>{label}</b>", pred_style))
    
    # Confidence and score
    conf_percent = round(confidence * 100) if isinstance(confidence, float) else confidence
    pred_details = f"Confidence: {conf_percent}% | Raw Score: {score:.4f}"
    story.append(Paragraph(pred_details, styles['BodyText']))
    
    calibration_note = model_output.get('calibrationNote', '')
    if calibration_note:
        story.append(Paragraph(f"<i>Note: {calibration_note}</i>", styles['SmallText']))
    
    story.append(Spacer(1, 6*mm))
    
    # ========== ATTENTION HEATMAP ==========
    if heatmap_image:
        story.append(Paragraph("Attention Heatmap", styles['SectionHeader']))
        story.append(Paragraph(
            "Regions highlighted in red/yellow indicate areas the model found most predictive. "
            "Blue regions contributed less to the final prediction.",
            styles['SmallText']
        ))
        story.append(Spacer(1, 3*mm))
        
        try:
            # Convert bytes to image
            img_buffer = io.BytesIO(heatmap_image)
            pil_img = Image.open(img_buffer)
            
            # Calculate dimensions to fit page width while preserving aspect ratio
            img_width, img_height = pil_img.size
            max_width = 160*mm
            max_height = 80*mm
            
            aspect = img_width / img_height
            if img_width > img_height:
                display_width = min(max_width, img_width)
                display_height = display_width / aspect
            else:
                display_height = min(max_height, img_height)
                display_width = display_height * aspect
            
            # Ensure fits
            if display_height > max_height:
                display_height = max_height
                display_width = display_height * aspect
            if display_width > max_width:
                display_width = max_width
                display_height = display_width / aspect
            
            # Create ReportLab image
            img_buffer.seek(0)
            rl_img = RLImage(img_buffer, width=display_width, height=display_height)
            story.append(rl_img)
            story.append(Spacer(1, 6*mm))
        except Exception as e:
            logger.error(f"Failed to embed heatmap: {e}")
            story.append(Paragraph(f"<i>[Heatmap unavailable: {str(e)}]</i>", styles['SmallText']))
    
    # ========== CLINICAL SUMMARY (MedGemma Report) ==========
    story.append(Paragraph("Clinical Summary", styles['SectionHeader']))
    
    summary = report_data.get('summary', 'No summary available.')
    # Clean up the summary text for PDF
    summary_clean = summary.replace('\n\n', '<br/><br/>').replace('\n', ' ')
    story.append(Paragraph(summary_clean, styles['BodyText']))
    story.append(Spacer(1, 6*mm))
    
    # ========== CLINICAL DECISION SUPPORT ==========
    decision_support = report_data.get('decisionSupport')
    if decision_support:
        story.append(Paragraph("Clinical Decision Support", styles['SectionHeader']))
        
        risk_level = decision_support.get('risk_level', 'unknown')
        confidence_level = decision_support.get('confidence_level', 'unknown')
        confidence_score = decision_support.get('confidence_score', 0)
        
        # Risk level indicator
        risk_colors = {
            'high_confidence': RESPONDER_GREEN,
            'moderate_confidence': WARNING_AMBER,
            'low_confidence': colors.orange,
            'inconclusive': NON_RESPONDER_RED,
        }
        risk_color = risk_colors.get(risk_level, colors.gray)
        
        story.append(Paragraph(
            f"<b>Risk Level:</b> {risk_level.replace('_', ' ').title()} | "
            f"<b>Confidence:</b> {confidence_level.title()} ({round(confidence_score * 100)}%)",
            styles['BodyText']
        ))
        
        # Primary recommendation
        primary_rec = decision_support.get('primary_recommendation', '')
        if primary_rec:
            story.append(Paragraph(f"<b>Primary Recommendation:</b> {primary_rec}", styles['BodyText']))
        
        # Supporting rationale
        rationale = decision_support.get('supporting_rationale', [])
        if rationale:
            story.append(Paragraph("<b>Supporting Evidence:</b>", styles['SubHeader']))
            for reason in rationale:
                story.append(Paragraph(f"• {reason}", styles['BodyText']))
        
        # Suggested workup
        workup = decision_support.get('suggested_workup', [])
        if workup:
            story.append(Paragraph("<b>Suggested Additional Workup:</b>", styles['SubHeader']))
            for i, step in enumerate(workup, 1):
                story.append(Paragraph(f"{i}. {step}", styles['BodyText']))
        
        # Quality warnings
        warnings = decision_support.get('quality_warnings', [])
        if warnings:
            story.append(Paragraph("<b>Quality Considerations:</b>", styles['SubHeader']))
            for warning in warnings:
                story.append(Paragraph(f"⚠ {warning}", styles['WarningText']))
        
        story.append(Spacer(1, 6*mm))
    
    # ========== SUPPORTING EVIDENCE ==========
    evidence = report_data.get('evidence', [])
    if evidence:
        story.append(Paragraph("Supporting Evidence", styles['SectionHeader']))
        story.append(Paragraph(
            f"Top {min(len(evidence), 5)} evidence patches contributing to the prediction:",
            styles['SmallText']
        ))
        story.append(Spacer(1, 3*mm))
        
        for i, item in enumerate(evidence[:5], 1):
            # Evidence item header
            coords = item.get('coordsLevel0', [])
            coords_str = f"({coords[0]:,}, {coords[1]:,})" if len(coords) >= 2 else "N/A"
            
            story.append(Paragraph(
                f"<b>Evidence #{i}</b> - Coordinates: {coords_str}",
                styles['SubHeader']
            ))
            
            # Morphology description
            morphology = item.get('morphologyDescription', 'No description available.')
            story.append(Paragraph(morphology, styles['BodyText']))
            
            # Why this patch matters
            significance = item.get('whyThisPatchMatters', '')
            if significance:
                story.append(Paragraph(
                    f"<font color='#006699'><b>Significance:</b> {significance}</font>",
                    styles['BodyText']
                ))
            
            story.append(Spacer(1, 3*mm))
    
    # ========== EVIDENCE PATCH IMAGES ==========
    if evidence_patches:
        story.append(PageBreak())
        story.append(Paragraph("Evidence Patch Gallery", styles['SectionHeader']))
        story.append(Paragraph(
            "High-attention patches that influenced the model prediction:",
            styles['SmallText']
        ))
        story.append(Spacer(1, 3*mm))
        
        # Create grid of patch images (3 per row)
        patch_row = []
        for i, patch in enumerate(evidence_patches[:9]):  # Max 9 patches
            if patch.get('image'):
                try:
                    img_buffer = io.BytesIO(patch['image'])
                    rl_img = RLImage(img_buffer, width=50*mm, height=50*mm)
                    
                    # Create cell with image and caption
                    caption = f"Patch #{i+1}\nAttn: {patch.get('attention', 0):.3f}"
                    cell_content = [
                        rl_img,
                        Paragraph(caption, styles['SmallText'])
                    ]
                    patch_row.append(cell_content)
                    
                    if len(patch_row) == 3:
                        # Create row table
                        row_table = Table([patch_row], colWidths=[55*mm, 55*mm, 55*mm])
                        row_table.setStyle(TableStyle([
                            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                        ]))
                        story.append(row_table)
                        story.append(Spacer(1, 5*mm))
                        patch_row = []
                except Exception as e:
                    logger.error(f"Failed to embed patch {i}: {e}")
        
        # Handle remaining patches
        if patch_row:
            while len(patch_row) < 3:
                patch_row.append('')
            row_table = Table([patch_row], colWidths=[55*mm, 55*mm, 55*mm])
            row_table.setStyle(TableStyle([
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ]))
            story.append(row_table)
    
    # ========== SIMILAR CASES ==========
    similar = report_data.get('similarExamples', [])
    if similar:
        story.append(Paragraph("Reference Cohort Comparison", styles['SectionHeader']))
        
        # Table header and data
        table_data = [['Case ID', 'Outcome', 'Distance']]
        for case in similar[:5]:
            case_id = case.get('exampleId', 'Unknown')[:24]
            outcome = case.get('label', 'N/A')
            distance = f"{case.get('distance', 0):.4f}"
            table_data.append([case_id, outcome, distance])
        
        similar_table = Table(table_data, colWidths=[80*mm, 50*mm, 35*mm])
        similar_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), ENSO_BLUE),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.gray),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.Color(248/255, 248/255, 248/255)]),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ]))
        story.append(similar_table)
        story.append(Spacer(1, 6*mm))
    
    # ========== SUGGESTED NEXT STEPS ==========
    next_steps = report_data.get('suggestedNextSteps', [])
    if next_steps:
        story.append(Paragraph("Suggested Next Steps", styles['SectionHeader']))
        for i, step in enumerate(next_steps, 1):
            story.append(Paragraph(f"<b>{i}.</b> {step}", styles['BodyText']))
        story.append(Spacer(1, 6*mm))
    
    # ========== LIMITATIONS ==========
    limitations = report_data.get('limitations', [])
    if limitations:
        story.append(Paragraph("Limitations", styles['SectionHeader']))
        for limitation in limitations:
            story.append(Paragraph(f"• {limitation}", styles['BodyText']))
        story.append(Spacer(1, 6*mm))
    
    # ========== SAFETY STATEMENT ==========
    safety = report_data.get('safetyStatement', '')
    if safety:
        story.append(Paragraph("Important Safety Notice", styles['SectionHeader']))
        
        safety_table = Table([[Paragraph(safety, styles['BodyText'])]], colWidths=[165*mm])
        safety_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.Color(255/255, 235/255, 235/255)),
            ('BOX', (0, 0), (-1, -1), 1, NON_RESPONDER_RED),
            ('LEFTPADDING', (0, 0), (-1, -1), 10),
            ('RIGHTPADDING', (0, 0), (-1, -1), 10),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ]))
        story.append(safety_table)
    
    # Build PDF
    doc.build(story, onFirstPage=create_header_footer, onLaterPages=create_header_footer)
    
    pdf_bytes = buffer.getvalue()
    buffer.close()
    
    return pdf_bytes


# ---------------------------------------------------------------------------
# Lightweight PDF generation using fpdf2 (pure Python, no system deps)
# ---------------------------------------------------------------------------

def generate_report_pdf(report: Dict[str, Any], case_id: str) -> bytes:
    """
    Generate a professional clinical pathology PDF report using fpdf2.

    This is a lightweight alternative to the ReportLab-based
    ``generate_pdf_report`` above.  It accepts the report JSON returned by
    ``POST /api/report`` and produces a self-contained PDF suitable for
    printing or archiving.

    Args:
        report: Structured report dict (from /api/report endpoint).
        case_id: Case identifier string.

    Returns:
        PDF file contents as bytes.
    """
    from fpdf import FPDF

    HEADER_TITLE = "Enso Atlas - Pathology Decision Support Report"
    FOOTER_TEXT = "Research use only - not for clinical diagnosis"

    class _ClinicalPDF(FPDF):
        """Custom FPDF subclass with header/footer for clinical reports."""

        def header(self):
            # Header bar
            self.set_fill_color(0, 102, 153)
            self.rect(0, 0, self.w, 22, style="F")
            self.set_font("Helvetica", "B", 13)
            self.set_text_color(255, 255, 255)
            self.set_y(4)
            self.cell(0, 8, HEADER_TITLE, align="C", new_x="LMARGIN", new_y="NEXT")
            self.set_font("Helvetica", "", 8)
            self.cell(0, 5, "AI-Assisted Diagnostic Platform", align="C",
                      new_x="LMARGIN", new_y="NEXT")
            self.ln(6)

        def footer(self):
            self.set_y(-15)
            self.set_font("Helvetica", "I", 7)
            self.set_text_color(120, 120, 120)
            self.cell(0, 10, f"{FOOTER_TEXT}  |  Page {self.page_no()}/{{nb}}",
                      align="C")

    pdf = _ClinicalPDF(orientation="P", unit="mm", format="A4")
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # ---- helpers --------------------------------------------------------
    def _section_heading(text: str):
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(0, 102, 153)
        pdf.cell(0, 8, text, new_x="LMARGIN", new_y="NEXT")
        pdf.set_draw_color(0, 102, 153)
        pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
        pdf.ln(2)

    def _label_value(label: str, value: str):
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(60, 60, 60)
        pdf.cell(40, 6, label, new_x="RIGHT")
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(0, 6, value, new_x="LMARGIN", new_y="NEXT")

    def _body_text(text: str):
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(30, 30, 30)
        pdf.multi_cell(0, 5, text)
        pdf.ln(1)

    def _bullet(text: str):
        x = pdf.get_x()
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(5, 5, "-")
        pdf.multi_cell(0, 5, text)

    # ---- Disclaimer banner ---------------------------------------------
    pdf.set_fill_color(255, 248, 225)
    pdf.set_draw_color(255, 193, 7)
    y_start = pdf.get_y()
    pdf.rect(pdf.l_margin, y_start, pdf.w - pdf.l_margin - pdf.r_margin, 14,
             style="DF")
    pdf.set_xy(pdf.l_margin + 2, y_start + 2)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(153, 102, 0)
    pdf.cell(0, 5, "UNCALIBRATED MODEL - RESEARCH USE ONLY",
             new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 8)
    pdf.cell(0, 5,
             "Probabilities are raw model outputs. Not validated for clinical "
             "decision-making.",
             new_x="LMARGIN", new_y="NEXT")
    pdf.set_y(y_start + 16)

    # ---- Case Information -----------------------------------------------
    _section_heading("Case Information")
    _label_value("Case ID:", case_id)
    task = report.get("task", "Treatment Response Prediction")
    _label_value("Task:", task)
    generated_at = report.get("generated_at",
                              report.get("generatedAt",
                                         datetime.now().strftime("%Y-%m-%d %H:%M")))
    _label_value("Date:", str(generated_at))
    pdf.ln(3)

    # ---- Prediction Section ---------------------------------------------
    model_output = report.get("model_output", report.get("modelOutput", {}))
    if model_output:
        _section_heading("Prediction")
        label = model_output.get("label", "Unknown")
        prob = model_output.get("probability",
                                model_output.get("score", 0))
        ci = model_output.get("confidence_interval",
                              model_output.get("confidenceInterval"))

        # Color-code prediction
        is_responder = "responder" in label.lower() and "non" not in label.lower()
        if is_responder:
            pdf.set_text_color(34, 139, 34)
        else:
            pdf.set_text_color(178, 34, 34)
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, label.upper(), new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(30, 30, 30)

        _label_value("Score:", f"{prob:.4f}" if isinstance(prob, float) else str(prob))
        if ci:
            _label_value("Confidence Interval:",
                         f"[{ci[0]:.4f}, {ci[1]:.4f}]"
                         if isinstance(ci, (list, tuple)) and len(ci) >= 2
                         else str(ci))
        cal_note = model_output.get("calibration_note",
                                    model_output.get("calibrationNote", ""))
        if cal_note:
            _label_value("Calibration Note:", cal_note)
        pdf.ln(2)

    # ---- Evidence Section -----------------------------------------------
    evidence_items = report.get("evidence", [])
    if evidence_items:
        _section_heading("Evidence")
        for i, item in enumerate(evidence_items[:10], 1):
            patch_id = item.get("patch_id", item.get("patchId", f"patch-{i}"))
            morphology = item.get("morphology_description",
                                  item.get("morphologyDescription", "N/A"))
            significance = item.get("significance",
                                    item.get("whyThisPatchMatters", ""))
            attention = item.get("attention_weight",
                                 item.get("attentionWeight"))

            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(0, 102, 153)
            header_parts = [f"Evidence #{i} ({patch_id})"]
            if attention is not None:
                header_parts.append(f"Attention: {float(attention):.4f}")
            pdf.cell(0, 6, "  |  ".join(header_parts),
                     new_x="LMARGIN", new_y="NEXT")
            pdf.set_text_color(30, 30, 30)
            _body_text(morphology)
            if significance:
                pdf.set_font("Helvetica", "I", 8)
                pdf.set_text_color(80, 80, 80)
                pdf.multi_cell(0, 4, f"Significance: {significance}")
                pdf.ln(1)
        pdf.ln(2)

    # ---- Similar Cases Section ------------------------------------------
    similar = report.get("similar_cases",
                         report.get("similarExamples", []))
    if similar:
        _section_heading("Similar Cases")
        # Table header
        col_w = [(pdf.w - pdf.l_margin - pdf.r_margin) * r
                 for r in (0.45, 0.30, 0.25)]
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_fill_color(0, 102, 153)
        pdf.set_text_color(255, 255, 255)
        for header, w in zip(["Case ID", "Outcome", "Distance"], col_w):
            pdf.cell(w, 6, header, border=1, fill=True, align="C")
        pdf.ln()
        pdf.set_text_color(30, 30, 30)
        pdf.set_font("Helvetica", "", 8)
        for idx, case in enumerate(similar[:8]):
            cid = str(case.get("exampleId", case.get("case_id", "N/A")))[:30]
            outcome = str(case.get("label", case.get("outcome", "N/A")))
            dist = case.get("distance", case.get("similarity_score", ""))
            dist_str = f"{float(dist):.4f}" if dist != "" else "N/A"
            if idx % 2 == 1:
                pdf.set_fill_color(245, 245, 245)
            else:
                pdf.set_fill_color(255, 255, 255)
            pdf.cell(col_w[0], 6, cid, border=1, fill=True, align="C")
            pdf.cell(col_w[1], 6, outcome, border=1, fill=True, align="C")
            pdf.cell(col_w[2], 6, dist_str, border=1, fill=True, align="C")
            pdf.ln()
        pdf.ln(3)

    # ---- Decision Support Section ---------------------------------------
    decision = report.get("decision_support",
                          report.get("decisionSupport"))
    if decision:
        _section_heading("Clinical Decision Support")
        rec = decision.get("primary_recommendation",
                           decision.get("primaryRecommendation", ""))
        if rec:
            _label_value("Recommendation:", rec)
        rationale = decision.get("supporting_rationale",
                                 decision.get("supportingRationale", []))
        if rationale:
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(60, 60, 60)
            pdf.cell(0, 6, "Supporting Evidence:", new_x="LMARGIN", new_y="NEXT")
            for r in rationale:
                _bullet(r)
        workup = decision.get("suggested_workup",
                              decision.get("suggestedWorkup", []))
        if workup:
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(60, 60, 60)
            pdf.cell(0, 6, "Suggested Workup:", new_x="LMARGIN", new_y="NEXT")
            for idx_w, w in enumerate(workup, 1):
                _body_text(f"{idx_w}. {w}")
        pdf.ln(2)

    # ---- Suggested Next Steps -------------------------------------------
    next_steps = report.get("suggested_next_steps",
                            report.get("suggestedNextSteps", []))
    if next_steps:
        _section_heading("Suggested Next Steps")
        for idx_s, step in enumerate(next_steps, 1):
            _body_text(f"{idx_s}. {step}")
        pdf.ln(2)

    # ---- Limitations ----------------------------------------------------
    limitations = report.get("limitations", [])
    if limitations:
        _section_heading("Limitations")
        for lim in limitations:
            _bullet(lim)
        pdf.ln(2)

    # ---- Safety Statement -----------------------------------------------
    safety = report.get("safety_statement",
                        report.get("safetyStatement", ""))
    if safety:
        _section_heading("Important Safety Notice")
        pdf.set_fill_color(255, 235, 235)
        pdf.set_draw_color(178, 34, 34)
        y0 = pdf.get_y()
        # Pre-calculate height needed
        pdf.set_font("Helvetica", "", 9)
        # Use a temporary approach - write then box
        x0 = pdf.l_margin + 3
        box_w = pdf.w - pdf.l_margin - pdf.r_margin
        pdf.set_xy(x0, y0 + 3)
        pdf.multi_cell(box_w - 6, 5, safety)
        y1 = pdf.get_y() + 3
        pdf.rect(pdf.l_margin, y0, box_w, y1 - y0, style="D")
        pdf.set_y(y1 + 2)

    # ---- Final footer disclaimer ----------------------------------------
    pdf.ln(5)
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 5, FOOTER_TEXT, align="C", new_x="LMARGIN", new_y="NEXT")

    return pdf.output()
