"""
Enso Atlas - Server-side PDF Export

Generates professional tumor board PDF reports using ReportLab.
Includes attention heatmaps and evidence patch images.
"""

import io
import logging
from datetime import datetime
from pathlib import Path
from typing import Optional, List, Dict, Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, mm
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Image as RLImage,
    PageBreak,
    KeepTogether,
    HRFlowable,
)
from reportlab.graphics.shapes import Drawing, Rect
from reportlab.pdfgen import canvas
from PIL import Image
import numpy as np

logger = logging.getLogger(__name__)

# Colors
ENSO_BLUE = colors.Color(0/255, 102/255, 153/255)
ENSO_BLUE_LIGHT = colors.Color(230/255, 242/255, 250/255)
RESPONDER_GREEN = colors.Color(34/255, 139/255, 34/255)
NON_RESPONDER_RED = colors.Color(178/255, 34/255, 34/255)
WARNING_AMBER = colors.Color(255/255, 193/255, 7/255)
WARNING_AMBER_BG = colors.Color(255/255, 248/255, 225/255)


def create_header_footer(canvas_obj, doc):
    """Add header and footer to each page."""
    canvas_obj.saveState()
    
    page_width, page_height = doc.pagesize
    
    # Header background
    canvas_obj.setFillColor(ENSO_BLUE)
    canvas_obj.rect(0, page_height - 40*mm, page_width, 40*mm, fill=1)
    
    # Header text
    canvas_obj.setFillColor(colors.white)
    canvas_obj.setFont("Helvetica-Bold", 16)
    canvas_obj.drawString(20*mm, page_height - 18*mm, "Pathology Analysis Report")
    
    canvas_obj.setFont("Helvetica", 10)
    canvas_obj.drawString(20*mm, page_height - 26*mm, "Enso Atlas | AI-Assisted Diagnostic Platform")
    
    # Date on right
    canvas_obj.drawRightString(page_width - 20*mm, page_height - 18*mm, 
                               datetime.now().strftime("%Y-%m-%d %H:%M"))
    
    # Footer
    canvas_obj.setFillColor(colors.gray)
    canvas_obj.setFont("Helvetica", 8)
    canvas_obj.drawCentredString(page_width/2, 15*mm, 
                                  f"Page {doc.page} | Generated by Enso Atlas v0.1.0 | For Research Use Only")
    
    canvas_obj.restoreState()


def get_styles():
    """Get custom paragraph styles."""
    styles = getSampleStyleSheet()
    
    # Custom styles
    styles.add(ParagraphStyle(
        name='SectionHeader',
        parent=styles['Heading2'],
        fontSize=12,
        textColor=ENSO_BLUE,
        spaceAfter=6,
        spaceBefore=12,
        borderWidth=0,
        borderPadding=0,
        borderColor=ENSO_BLUE,
        borderRadius=0,
    ))
    
    styles.add(ParagraphStyle(
        name='SubHeader',
        parent=styles['Heading3'],
        fontSize=10,
        textColor=colors.black,
        spaceAfter=4,
        spaceBefore=8,
    ))
    
    styles.add(ParagraphStyle(
        name='EnsoBody',
        parent=styles['Normal'],
        fontSize=10,
        leading=14,
        alignment=TA_JUSTIFY,
        spaceAfter=6,
    ))
    # Also update the default BodyText
    styles['BodyText'].fontSize = 10
    styles['BodyText'].leading = 14
    styles['BodyText'].alignment = TA_JUSTIFY
    styles['BodyText'].spaceAfter = 6
    
    styles.add(ParagraphStyle(
        name='SmallText',
        parent=styles['Normal'],
        fontSize=8,
        leading=10,
        textColor=colors.gray,
    ))
    
    styles.add(ParagraphStyle(
        name='WarningText',
        parent=styles['Normal'],
        fontSize=9,
        leading=12,
        textColor=colors.Color(153/255, 102/255, 0),
        backColor=WARNING_AMBER_BG,
    ))
    
    styles.add(ParagraphStyle(
        name='PredictionResponder',
        parent=styles['Heading1'],
        fontSize=14,
        textColor=RESPONDER_GREEN,
        alignment=TA_LEFT,
    ))
    
    styles.add(ParagraphStyle(
        name='PredictionNonResponder',
        parent=styles['Heading1'],
        fontSize=14,
        textColor=NON_RESPONDER_RED,
        alignment=TA_LEFT,
    ))
    
    return styles


def create_info_table(data: List[List[str]], col_widths: List[float]) -> Table:
    """Create a styled info table."""
    table = Table(data, colWidths=col_widths)
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.Color(245/255, 245/255, 245/255)),
        ('TEXTCOLOR', (0, 0), (0, -1), colors.black),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('ALIGN', (0, 0), (0, -1), 'RIGHT'),
        ('ALIGN', (1, 0), (1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]))
    return table


def generate_pdf_report(
    slide_id: str,
    report_data: Dict[str, Any],
    prediction_data: Dict[str, Any],
    heatmap_image: Optional[bytes] = None,
    evidence_patches: Optional[List[Dict[str, Any]]] = None,
    institution_name: str = "Enso Labs",
    patient_context: Optional[Dict[str, Any]] = None,
) -> bytes:
    """
    Generate a professional PDF report for tumor board presentation.
    
    Args:
        slide_id: Slide identifier
        report_data: Structured report from MedGemma (StructuredReport dict)
        prediction_data: Model prediction results
        heatmap_image: PNG bytes of attention heatmap
        evidence_patches: List of evidence patch data with images
        institution_name: Institution name for header
        patient_context: Patient demographic info
    
    Returns:
        PDF file as bytes
    """
    buffer = io.BytesIO()
    
    # Create document
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=20*mm,
        leftMargin=20*mm,
        topMargin=45*mm,  # Space for header
        bottomMargin=25*mm,
    )
    
    styles = get_styles()
    story = []
    
    # ========== UNCALIBRATED WARNING ==========
    warning_text = """
    <b>⚠ UNCALIBRATED MODEL - RESEARCH USE ONLY</b><br/>
    Probabilities are raw model outputs. Not validated for clinical decision-making.
    All findings must be verified by qualified pathologists before clinical use.
    """
    warning_para = Paragraph(warning_text, styles['WarningText'])
    warning_table = Table([[warning_para]], colWidths=[170*mm])
    warning_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), WARNING_AMBER_BG),
        ('BOX', (0, 0), (-1, -1), 2, WARNING_AMBER),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(warning_table)
    story.append(Spacer(1, 10*mm))
    
    # ========== CASE INFORMATION ==========
    story.append(Paragraph("Case Information", styles['SectionHeader']))
    
    case_id = report_data.get('caseId', 'N/A')
    generated_at = report_data.get('generatedAt', datetime.now().isoformat())
    task = report_data.get('task', 'Treatment Response Prediction')
    
    info_data = [
        ['Case ID:', case_id],
        ['Slide ID:', slide_id],
        ['Task:', task],
        ['Generated:', datetime.fromisoformat(generated_at.replace('Z', '+00:00')).strftime('%Y-%m-%d %H:%M UTC') if generated_at else 'N/A'],
    ]
    
    story.append(create_info_table(info_data, [35*mm, 130*mm]))
    story.append(Spacer(1, 6*mm))
    
    # ========== PATIENT CONTEXT ==========
    if patient_context:
        story.append(Paragraph("Patient Information", styles['SectionHeader']))
        
        patient_data = []
        if patient_context.get('age'):
            patient_data.append(['Age:', str(patient_context['age'])])
        if patient_context.get('sex'):
            patient_data.append(['Sex:', patient_context['sex']])
        if patient_context.get('stage'):
            patient_data.append(['Stage:', patient_context['stage']])
        if patient_context.get('grade'):
            patient_data.append(['Grade:', patient_context['grade']])
        if patient_context.get('histology'):
            patient_data.append(['Histology:', patient_context['histology']])
        if patient_context.get('prior_lines') is not None:
            patient_data.append(['Prior Lines:', str(patient_context['prior_lines'])])
        
        if patient_data:
            story.append(create_info_table(patient_data, [35*mm, 130*mm]))
            story.append(Spacer(1, 6*mm))
    
    # ========== MODEL PREDICTION ==========
    story.append(Paragraph("Model Prediction", styles['SectionHeader']))
    
    model_output = report_data.get('modelOutput', prediction_data)
    label = model_output.get('label', prediction_data.get('prediction', 'Unknown'))
    score = model_output.get('score', prediction_data.get('score', 0))
    confidence = model_output.get('confidence', prediction_data.get('confidence', 0))
    
    # Determine style based on prediction
    is_responder = 'responder' in label.lower() and 'non' not in label.lower()
    pred_style = styles['PredictionResponder'] if is_responder else styles['PredictionNonResponder']
    
    story.append(Paragraph(f"<b>{label}</b>", pred_style))
    
    # Confidence and score
    conf_percent = round(confidence * 100) if isinstance(confidence, float) else confidence
    pred_details = f"Confidence: {conf_percent}% | Raw Score: {score:.4f}"
    story.append(Paragraph(pred_details, styles['BodyText']))
    
    calibration_note = model_output.get('calibrationNote', '')
    if calibration_note:
        story.append(Paragraph(f"<i>Note: {calibration_note}</i>", styles['SmallText']))
    
    story.append(Spacer(1, 6*mm))
    
    # ========== ATTENTION HEATMAP ==========
    if heatmap_image:
        story.append(Paragraph("Attention Heatmap", styles['SectionHeader']))
        story.append(Paragraph(
            "Regions highlighted in red/yellow indicate areas the model found most predictive. "
            "Blue regions contributed less to the final prediction.",
            styles['SmallText']
        ))
        story.append(Spacer(1, 3*mm))
        
        try:
            # Convert bytes to image
            img_buffer = io.BytesIO(heatmap_image)
            pil_img = Image.open(img_buffer)
            
            # Calculate dimensions to fit page width while preserving aspect ratio
            img_width, img_height = pil_img.size
            max_width = 160*mm
            max_height = 80*mm
            
            aspect = img_width / img_height
            if img_width > img_height:
                display_width = min(max_width, img_width)
                display_height = display_width / aspect
            else:
                display_height = min(max_height, img_height)
                display_width = display_height * aspect
            
            # Ensure fits
            if display_height > max_height:
                display_height = max_height
                display_width = display_height * aspect
            if display_width > max_width:
                display_width = max_width
                display_height = display_width / aspect
            
            # Create ReportLab image
            img_buffer.seek(0)
            rl_img = RLImage(img_buffer, width=display_width, height=display_height)
            story.append(rl_img)
            story.append(Spacer(1, 6*mm))
        except Exception as e:
            logger.error(f"Failed to embed heatmap: {e}")
            story.append(Paragraph(f"<i>[Heatmap unavailable: {str(e)}]</i>", styles['SmallText']))
    
    # ========== CLINICAL SUMMARY (MedGemma Report) ==========
    story.append(Paragraph("Clinical Summary", styles['SectionHeader']))
    
    summary = report_data.get('summary', 'No summary available.')
    # Clean up the summary text for PDF
    summary_clean = summary.replace('\n\n', '<br/><br/>').replace('\n', ' ')
    story.append(Paragraph(summary_clean, styles['BodyText']))
    story.append(Spacer(1, 6*mm))
    
    # ========== CLINICAL DECISION SUPPORT ==========
    decision_support = report_data.get('decisionSupport')
    if decision_support:
        story.append(Paragraph("Clinical Decision Support", styles['SectionHeader']))
        
        risk_level = decision_support.get('risk_level', 'unknown')
        confidence_level = decision_support.get('confidence_level', 'unknown')
        confidence_score = decision_support.get('confidence_score', 0)
        
        # Risk level indicator
        risk_colors = {
            'high_confidence': RESPONDER_GREEN,
            'moderate_confidence': WARNING_AMBER,
            'low_confidence': colors.orange,
            'inconclusive': NON_RESPONDER_RED,
        }
        risk_color = risk_colors.get(risk_level, colors.gray)
        
        story.append(Paragraph(
            f"<b>Risk Level:</b> {risk_level.replace('_', ' ').title()} | "
            f"<b>Confidence:</b> {confidence_level.title()} ({round(confidence_score * 100)}%)",
            styles['BodyText']
        ))
        
        # Primary recommendation
        primary_rec = decision_support.get('primary_recommendation', '')
        if primary_rec:
            story.append(Paragraph(f"<b>Primary Recommendation:</b> {primary_rec}", styles['BodyText']))
        
        # Supporting rationale
        rationale = decision_support.get('supporting_rationale', [])
        if rationale:
            story.append(Paragraph("<b>Supporting Evidence:</b>", styles['SubHeader']))
            for reason in rationale:
                story.append(Paragraph(f"• {reason}", styles['BodyText']))
        
        # Suggested workup
        workup = decision_support.get('suggested_workup', [])
        if workup:
            story.append(Paragraph("<b>Suggested Additional Workup:</b>", styles['SubHeader']))
            for i, step in enumerate(workup, 1):
                story.append(Paragraph(f"{i}. {step}", styles['BodyText']))
        
        # Quality warnings
        warnings = decision_support.get('quality_warnings', [])
        if warnings:
            story.append(Paragraph("<b>Quality Considerations:</b>", styles['SubHeader']))
            for warning in warnings:
                story.append(Paragraph(f"⚠ {warning}", styles['WarningText']))
        
        story.append(Spacer(1, 6*mm))
    
    # ========== SUPPORTING EVIDENCE ==========
    evidence = report_data.get('evidence', [])
    if evidence:
        story.append(Paragraph("Supporting Evidence", styles['SectionHeader']))
        story.append(Paragraph(
            f"Top {min(len(evidence), 5)} evidence patches contributing to the prediction:",
            styles['SmallText']
        ))
        story.append(Spacer(1, 3*mm))
        
        for i, item in enumerate(evidence[:5], 1):
            # Evidence item header
            coords = item.get('coordsLevel0', [])
            coords_str = f"({coords[0]:,}, {coords[1]:,})" if len(coords) >= 2 else "N/A"
            
            story.append(Paragraph(
                f"<b>Evidence #{i}</b> - Coordinates: {coords_str}",
                styles['SubHeader']
            ))
            
            # Morphology description
            morphology = item.get('morphologyDescription', 'No description available.')
            story.append(Paragraph(morphology, styles['BodyText']))
            
            # Why this patch matters
            significance = item.get('whyThisPatchMatters', '')
            if significance:
                story.append(Paragraph(
                    f"<font color='#006699'><b>Significance:</b> {significance}</font>",
                    styles['BodyText']
                ))
            
            story.append(Spacer(1, 3*mm))
    
    # ========== EVIDENCE PATCH IMAGES ==========
    if evidence_patches:
        story.append(PageBreak())
        story.append(Paragraph("Evidence Patch Gallery", styles['SectionHeader']))
        story.append(Paragraph(
            "High-attention patches that influenced the model prediction:",
            styles['SmallText']
        ))
        story.append(Spacer(1, 3*mm))
        
        # Create grid of patch images (3 per row)
        patch_row = []
        for i, patch in enumerate(evidence_patches[:9]):  # Max 9 patches
            if patch.get('image'):
                try:
                    img_buffer = io.BytesIO(patch['image'])
                    rl_img = RLImage(img_buffer, width=50*mm, height=50*mm)
                    
                    # Create cell with image and caption
                    caption = f"Patch #{i+1}\nAttn: {patch.get('attention', 0):.3f}"
                    cell_content = [
                        rl_img,
                        Paragraph(caption, styles['SmallText'])
                    ]
                    patch_row.append(cell_content)
                    
                    if len(patch_row) == 3:
                        # Create row table
                        row_table = Table([patch_row], colWidths=[55*mm, 55*mm, 55*mm])
                        row_table.setStyle(TableStyle([
                            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                        ]))
                        story.append(row_table)
                        story.append(Spacer(1, 5*mm))
                        patch_row = []
                except Exception as e:
                    logger.error(f"Failed to embed patch {i}: {e}")
        
        # Handle remaining patches
        if patch_row:
            while len(patch_row) < 3:
                patch_row.append('')
            row_table = Table([patch_row], colWidths=[55*mm, 55*mm, 55*mm])
            row_table.setStyle(TableStyle([
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ]))
            story.append(row_table)
    
    # ========== SIMILAR CASES ==========
    similar = report_data.get('similarExamples', [])
    if similar:
        story.append(Paragraph("Reference Cohort Comparison", styles['SectionHeader']))
        
        # Table header and data
        table_data = [['Case ID', 'Outcome', 'Distance']]
        for case in similar[:5]:
            case_id = case.get('exampleId', 'Unknown')[:24]
            outcome = case.get('label', 'N/A')
            distance = f"{case.get('distance', 0):.4f}"
            table_data.append([case_id, outcome, distance])
        
        similar_table = Table(table_data, colWidths=[80*mm, 50*mm, 35*mm])
        similar_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), ENSO_BLUE),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.gray),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.Color(248/255, 248/255, 248/255)]),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ]))
        story.append(similar_table)
        story.append(Spacer(1, 6*mm))
    
    # ========== SUGGESTED NEXT STEPS ==========
    next_steps = report_data.get('suggestedNextSteps', [])
    if next_steps:
        story.append(Paragraph("Suggested Next Steps", styles['SectionHeader']))
        for i, step in enumerate(next_steps, 1):
            story.append(Paragraph(f"<b>{i}.</b> {step}", styles['BodyText']))
        story.append(Spacer(1, 6*mm))
    
    # ========== LIMITATIONS ==========
    limitations = report_data.get('limitations', [])
    if limitations:
        story.append(Paragraph("Limitations", styles['SectionHeader']))
        for limitation in limitations:
            story.append(Paragraph(f"• {limitation}", styles['BodyText']))
        story.append(Spacer(1, 6*mm))
    
    # ========== SAFETY STATEMENT ==========
    safety = report_data.get('safetyStatement', '')
    if safety:
        story.append(Paragraph("Important Safety Notice", styles['SectionHeader']))
        
        safety_table = Table([[Paragraph(safety, styles['BodyText'])]], colWidths=[165*mm])
        safety_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.Color(255/255, 235/255, 235/255)),
            ('BOX', (0, 0), (-1, -1), 1, NON_RESPONDER_RED),
            ('LEFTPADDING', (0, 0), (-1, -1), 10),
            ('RIGHTPADDING', (0, 0), (-1, -1), 10),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ]))
        story.append(safety_table)
    
    # Build PDF
    doc.build(story, onFirstPage=create_header_footer, onLaterPages=create_header_footer)
    
    pdf_bytes = buffer.getvalue()
    buffer.close()
    
    return pdf_bytes
